### ISSUE TITLE
implicit state_topic is deprecated

### ISSUE THREAD

**Issue by bjornta** [quazzie/tellstick-plugin-mqtt-hass#10]
Upgraded from 0.82.3 to 0.84, and got these messages in HA for all devices:

implicit state_topic is deprecated, add "state_topic":"elghaugen/sensor/znet/ACCA5401F795_1196_battery/state" to elghaugen/sensor/znet/ACCA5401F795_1196_battery/config discovery message

Upgrade was performed by uninstalling 0.82.3 and then installing 0.84.
Everything (else) seems to be working fine though.

**Comment by quazzie** [comment]
Hmm it should not use implicit state_topic.
Maybe some left over config from old version / uninstall.
I would clear all retained messages for "elghaugen/sensors/znet/#" and reboot the tellstick to get back on track. As far as i know there is no simple way to clear all the messages, just some scripts that can help with multiple topics.

Maybe start with only removing the problematic sensor:
```
mosquitto_pub -t "elghaugen/sensors/znet/ACCA5401F795_1196_battery/config" -n -r
mosquitto_pub -t "elghaugen/sensors/znet/ACCA5401F795_1196_battery/state" -n -r
```
If the sensor is still relevant it should reappear on reboot of tellstick.

**Comment by bjornta** [comment]
I removed all the retained topics, but after reboot they came back. I did this twice with the same result.

**Comment by quazzie** [comment]
What version of HA do you have? 
I get no such messages in 0.105.4

Could you capture topics 'telldus/znet/debug' and 'elghaugen/+/znet/#' on Tellstick boot?

**Comment by bjornta** [comment]
I'm running 104.3. 
Will get topics when I can reboot the Telldus soon.

**Comment by lillebry** [comment]
same issue.. any sulution?

**Comment by quazzie** [comment]
@lillebry could you capture the mqtt topics specified above ?
And it should not be required to capture them at boot as they are retained.
```mosquitto_sub -t "homeassistant/+/+/+/config" -v```
All my entities has topic_state defined, i don't see what type is using implicit state_topic..

**Comment by bjornta** [comment]
[_Download.zip](https://github.com/quazzie/tellstick-plugin-mqtt-hass/files/4246248/_Download.zip)
Here's my config-messages.

**Comment by quazzie** [comment]
@bjornta thanks!
Found the problem, fixed in https://github.com/quazzie/tellstick-plugin-mqtt-hass/releases/tag/0.85
I had missed state_topic for battery sensors.

Please update and see if it is gone and report back.
To update just go to tellstick plugin page and upload new version then reboot when it asks to be rebooted.

**Comment by bjornta** [comment]
The error-messages disappeared.
However, when renaming a device in Telldus it doesn't reflect in HA for the battery part of the device. The rest of the device is renamed correctly.
Battery status is correct though. All my devices show 100%, which is correct.

**Comment by quazzie** [comment]
Hmm sensor names gets created the same way.
But if the device is already added to HA changing its name in telldus will not change it's name in HA.
Thats just how mqtt discovery works.

Closing this, thanks for the help.
