### ISSUE TITLE
Does not update available status to online

### ISSUE THREAD

**Issue by fredrike** [quazzie/tellstick-plugin-mqtt-hass#11]
For some reason the telldus publish `telldus/telldus/available offline` and don't seem to update to `online`.

My telldus is apparently `available` (as it publish data on MQTT)..

```
telldus/telldus/available offline
telldus/telldus/debug {"scale": 2, "battery": null, "valueType": 256, "value": 0.0, "deviceId": 2, "type": "sensorValueUpdated"}
telldus/telldus/debug sensorState {'scale': 2, 'lastUpdated': 1584094573, 'value': '0.0'}
telldus/telldus/debug {"scale": 2, "battery": null, "valueType": 256, "value": 0.0, "deviceId": 1, "type": "sensorValueUpdated"}
telldus/telldus/debug sensorState {'scale': 2, 'lastUpdated': 1584094574, 'value': '0.0'}
telldus/telldus/debug {"scale": 0, "battery": 254, "valueType": 1, "value": 6.5, "deviceId": 11, "type": "sensorValueUpdated"}
telldus/telldus/debug sensorState {'scale': 0, 'lastUpdated': 1584094577, 'value': '6.5'}
telldus/telldus/debug {"protocol": "fineoffset", "id": 255, "values": [{"scale": 0, "type": 1, "value": 6.5}], "model": "temperature", "data": 68455366565, "class": "sensor"}
telldus/telldus/debug {"scale": 0, "battery": 254, "valueType": 1, "value": 8.6999999999999993, "deviceId": 121, "type": "sensorValueUpdated"}
telldus/telldus/debug sensorState {'scale': 0, 'lastUpdated': 1584094578, 'value': '8.7'}
telldus/telldus/debug {"protocol": "fineoffset", "id": 199, "values": [{"scale": 0, "type": 1, "value": 8.6999999999999993}, {"scale": 0, "type": 2, "value": 66}], "model": "temperaturehumidity", "data": 328302281419, "class": "sensor"}
```

_Originally posted by @fredrike in https://github.com/quazzie/tellstick-plugin-mqtt-hass/issues/9#issuecomment-598650462_

**Comment by fredrike** [comment]
Pushing a `online` state makes it work again.

`mosquitto_pub -t telldus/telldus/available -r -m "online"`

**Comment by quazzie** [comment]
Uhm, this is so strange.
Works as intended here, onConnect gets called on reconnect and available set to online.
Killed the connection several times and available get set to offline, then everytime it reconnects it calls onConnect and sets available to online again.
I'll try to debug some more and see what i can find.

**Comment by fredrike** [comment]
It actually might be some incompatibilities between my mqtt-server ..

I'm running https://hub.docker.com/_/eclipse-mosquitto with this configuration, perhaps it is something that causes issues..

```cfg
password_file /mosquitto/config/passwd_file
allow_anonymous false
persistence true
persistence_file mosquitto.db
persistence_location /mosquitto/data/
autosave_on_changes true
```

**Comment by fredrike** [comment]
It is definitely my mosquitto server that is acting weird. How have you configured your mqtt server and which are you running?

**Comment by uphillbattle** [comment]
For what it's worth: 
I'm running the (Eclipse) Mosquitto broker offered as an official add-on to hass.io (running all of it in Docker on an Intel NUC). I have not noticed any problems with the mqtt server.

My configuration of the Mosquitto broker add-on is:

```
logins:
  - username: <username>
    password: <password>
anonymous: false
customize:
  active: false
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false
```

**Comment by quazzie** [comment]
I run mosquitto in my host system. 
apt get mosquitto, default config.

**Comment by fredrike** [comment]
Cool!

I installed the https://github.com/home-assistant/hassio-addons/tree/master/mosquitto addon and it seems to be running much more stable now.

So, there is an issue with the configuration I had and the official libraries..

**Comment by fredrike** [comment]
I still have the same behavior..

**Comment by quazzie** [comment]
I still have not found anything. You got any new info ?

**Comment by fredrike** [comment]
It is on my mqtt side so will close this..
