### ISSUE TITLE
Add support to add multiple devices

### ISSUE THREAD

**Issue by fredrike** [quazzie/tellstick-plugin-mqtt-hass#13]
The way Home-Assistant works with devices is the following:

- A device can have multiple entities (where an entity is a sensor, a switch, a lamp etc.). 
- A device can be assigned to an area. 
- A device can be nested under another device (using the `via_device` property https://github.com/home-assistant/core/pull/19454).

That means that in the Telldus environment each sensor should be its own device and this device should be nested under the Tellstick-device.

This is how the sensor "Vit Inne"  in the Tellstick-live integration (Mjövik is the name of my Tellstick-Lite):
<img width="348" alt="Screenshot 2020-03-22 at 9 32 54 " src="https://user-images.githubusercontent.com/676999/77245744-31983280-6c21-11ea-9cac-b58626d026df.png">
<img width="326" alt="Screenshot 2020-03-22 at 9 42 03 " src="https://user-images.githubusercontent.com/676999/77245781-72904700-6c21-11ea-88da-2ca85ab9fd75.png">

I therefore suggest that this plugin sends a `binary_sensor` that represents the Tellstick like this:

`homeassistant/binary_sensor/telldus/ACCA5401B5EA/config`

```json
{"name": "Telldus", "payload_off": "offline", "payload_on": "online", "device": {"sw_version": "1.3.1", "name": "telldus", "identifiers": "ACCA5401B5EA", "connections": [["mac", "AC:CA:54:01:B5:EA"]], "model": "tellstick-znet-lite-v2", "manufacturer": "Telldus Technologies"}, "device_class": "connectivity", "state_topic": "telldus/telldus/available", "availability_topic": "telldus/telldus/available", "unique_id": "ACCA5401B5EA_main"}
```

And that this entities (posted to `homeassistant/sensor/telldus/6_1_0/config`, `homeassistant/sensor/telldus/6_2_0/config` & `homeassistant/sensor/telldus/ACCA5401B5EA_6_battery/config`:
```json
{"unit_of_measurement": "\u00b0C", "json_attributes_topic": "home/sensor/telldus/6_1_0/state", "name": "Vit Inne temp - \u00b0C", "value_template": "{{ value_json.value }}", "device": {"sw_version": "1.3.1", "name": "telldus", "identifiers": "ACCA5401B5EA", "connections": [["mac", "AC:CA:54:01:B5:EA"]], "model": "tellstick-znet-lite-v2", "manufacturer": "Telldus Technologies"}, "device_class": "temperature", "state_topic": "home/sensor/telldus/6_1_0/state", "availability_topic": "telldus/telldus/available", "unique_id": "ACCA5401B5EA_6_1_0"}
{"unit_of_measurement": "%", "json_attributes_topic": "home/sensor/telldus/6_2_0/state", "name": "Vit Inne humidity - %", "value_template": "{{ value_json.value }}", "device": {"sw_version": "1.3.1", "name": "telldus", "identifiers": "ACCA5401B5EA", "connections": [["mac", "AC:CA:54:01:B5:EA"]], "model": "tellstick-znet-lite-v2", "manufacturer": "Telldus Technologies"}, "device_class": "humidity", "state_topic": "home/sensor/telldus/6_2_0/state", "availability_topic": "telldus/telldus/available", "unique_id": "ACCA5401B5EA_6_2_0"}
{"unit_of_measurement": "%", "device": {"sw_version": "1.3.1", "name": "telldus", "identifiers": "ACCA5401B5EA", "connections": [["mac", "AC:CA:54:01:B5:EA"]], "model": "tellstick-znet-lite-v2", "manufacturer": "Telldus Technologies"}, "name": "Vit Inne - Battery", "device_class": "battery", "state_topic": "home/sensor/telldus/ACCA5401B5EA_6_battery/state", "availability_topic": "telldus/telldus/available", "unique_id": "ACCA5401B5EA_ACCA5401B5EA_6_battery"}
```

Are changed to:
```json
{"unit_of_measurement": "\u00b0C", "json_attributes_topic": "home/sensor/telldus/6_1_0/state", "name": "Vit Inne temp - \u00b0C", "value_template": "{{ value_json.value }}", "device": {"name": "Vit Inne", "identifiers": "ACCA5401B5EA-vit_inne", "connections": [["mac", "AC:CA:54:01:B5:EA"]], "via_device": "ACCA5401B5EA"}, "device_class": "temperature", "state_topic": "home/sensor/telldus/6_1_0/state", "availability_topic": "telldus/telldus/available", "unique_id": "ACCA5401B5EA_6_1_0"}
{"unit_of_measurement": "%", "json_attributes_topic": "home/sensor/telldus/6_2_0/state", "name": "Vit Inne humidity - %", "value_template": "{{ value_json.value }}", "device": {"name": "Vit Inne", "identifiers": "ACCA5401B5EA-vit_inne", "connections": [["mac", "AC:CA:54:01:B5:EA"]], "via_device": "ACCA5401B5EA"}, "device_class": "humidity", "state_topic": "home/sensor/telldus/6_2_0/state", "availability_topic": "telldus/telldus/available", "unique_id": "ACCA5401B5EA_6_2_0"}
{"unit_of_measurement": "%", "device": {"name": "Vit Inne", "identifiers": "ACCA5401B5EA-vit_inne", "connections": [["mac", "AC:CA:54:01:B5:EA"]], "via_device": "ACCA5401B5EA"}, "name": "Vit Inne - Battery", "device_class": "battery", "state_topic": "home/sensor/telldus/ACCA5401B5EA_6_battery/state", "availability_topic": "telldus/telldus/available", "unique_id": "ACCA5401B5EA_ACCA5401B5EA_6_battery"}
```

I don't know if "model" & "manufacturer" is available at the plugin level but perhaps "model" could represent the type of device.

**Comment by fredrike** [comment]
`ACCA5401B5EA-vit_inne` could be created by using slugify just as done here:
https://github.com/home-assistant/core/blob/master/homeassistant/util/__init__.py#L47

i.e.

```py

from slugify import slugify

ident = f"{mac}-{slugify(name, separator='_'}"
```

**Comment by fredrike** [comment]
@quazzie: your code really looks amazing, I think I might be able to wrap multiple devices together myself..

My idea is to add a helper function for `publish_discovery()` that uses via_device (I've even documented it now:https://github.com/home-assistant/home-assistant.io/pull/12671 )
https://github.com/quazzie/tellstick-plugin-mqtt-hass/blob/8b3d33af29b7b3a8a0d242048f04d6ad758d9c19/hass_client/Client.py#L414-L437

What do you think of it?

**Comment by quazzie** [comment]
Thanks! Sorry i have not had time to look at this.

I tried you pr on my dev tellstick, seems to work as you describe. 
Maybe a problem on HA's end but i think this is a lot more confusing :) 
I can't see all my tellstick devices in one place, having a hard time finding them all, is it suppose to be like that?

Before i could just go to devices - tellstick and get all my sensors/devices.

**Comment by fredrike** [comment]
The idea is to go to Integrations -> MQTT and there you can see all Devices..

From one Device you should be able to see Entites and parents..

Look at the Related tab (and hopefully there should be a 
hierarchy).
![Screenshot 2020-04-07 at 11 22 27 ](https://user-images.githubusercontent.com/676999/78652480-133d6280-78c2-11ea-954e-135388043861.png)

Could you upload the test version so I can test it?

**Comment by quazzie** [comment]
[MQTT_Homeassistant-0.85.zip](https://github.com/quazzie/tellstick-plugin-mqtt-hass/files/4443232/MQTT_Homeassistant-0.85.zip)

**Comment by fredrike** [comment]
Do you want me to make this optional via configuration?

**Comment by fredrike** [comment]
This is not right:

```json
homeassistant/<type 'type'>/telldus/hub/config {"availability_topic": "telldus/telldus/available", "name": "telldus", "payload_on": "online", "device": {"sw_version": "1.3.1", "name": "telldus", "identifiers": "ACCA5401B5EA", "connections": [["mac", "AC:CA:54:01:B5:EA"]], "model": "tellstick-znet-lite-v2", "manufacturer": "Telldus Technologies"}, "device_class": "connectivity", "state_topic": "telldus/telldus/available", "payload_off": "offline", "unique_id": "ACCA5401B5EA_hub"}
```

Hm, the hierarchy does not seem to work either..

**Comment by quazzie** [comment]
[MQTT_Homeassistant-0.85.1.zip](https://github.com/quazzie/tellstick-plugin-mqtt-hass/files/4443568/MQTT_Homeassistant-0.85.1.zip)
Fixed <type 'type'> to binary_sensor

**Comment by fredrike** [comment]
I do think this is the intended way Devices should work. There is hierarchy but it is not shown in the frontend (yet). 

What do you think about setting `Device.protocol().title()` as `device.manufacturer`?

Also, the `device_name` used in topic must be sluggified according to: https://www.home-assistant.io/docs/mqtt/discovery/ (node_id)

**Comment by fredrike** [comment]
Vi kanske ska skippa min unique_id ändring också, det kommer ju ändra alla devices och bli en "Breaking change" på gamla entiteter.

**Comment by fredrike** [comment]
I've updated the code in my PR..
