### ISSUE TITLE
Sluggify base_topic and device_name

### ISSUE THREAD

**Issue by fredrike** [quazzie/tellstick-plugin-mqtt-hass#15]
Both base_topic and device_name should be slugified like this (not sure that it is allowed to add external libs):

http://code.activestate.com/recipes/577257-slugify-make-a-string-usable-in-a-url-or-filename/

**Comment by quazzie** [comment]
Uhm external libs are fine but slugify did not, lots of errors.
I did my own slugify for now.
#fixed 0.86
