### ISSUE TITLE
Importing of custom keys are not allowed

### ISSUE THREAD

**Issue by acateon** [quazzie/tellstick-plugin-mqtt-hass#18]
Försöker lägga till pluginet men får följande felbeskrivning:

```
Error importing plugin
Plugin could not be imported:

Importing of custom keys are not allowed
```
För det är zip-filen (MQTT_Homeassistant-0.86.zip) som skall laddas upp i Tellsticken?

**Comment by uphillbattle** [comment]
Har du fått Telldus support til å legge til muligheten for lokal plugin?

![image](https://user-images.githubusercontent.com/15340540/90503775-49340280-e150-11ea-96a0-9b18f77a4069.png)

**Comment by acateon** [comment]
Får inte upp trusted developers och möjligtvis inte lokala plugins, dock möjlighet att ladda upp (se bild). Har dock gjort en ticket till Telldus om det som skrevs i readme'n.

![Skärmavbild 2020-08-18 kl  12 47 34](https://user-images.githubusercontent.com/14361705/90504333-353cd080-e151-11ea-87ba-7041aea4a84f.png)

**Comment by uphillbattle** [comment]
Vent til Telldus support har lagt til quazzie som "trusted developer" på din Tellstick. Det går ikke å laste opp quazzie's plugin før han er satt som "trusted developer". Forsøk deretter å laste opp plugin på ny.

**Comment by acateon** [comment]
All right, tack för hjälpen!
