### ISSUE TITLE
Battery sensor entity not renamed

### ISSUE THREAD

**Issue by rodakswe** [quazzie/tellstick-plugin-mqtt-hass#19]
Hi,

Yesterday I renamed one of my sensors in Telldus Live.
This one repports Temperature/Humidity/Battery.

While temperature and humidity got renamed properly in Home Assistant, the battery sensor still has the old name/entity id.
Any idea how to solve that without renaming manually in Home Assistant?

Example old name in Telldus Live:
Vardagsrum
Gave following entities in Home Assistant:
sensor.vardagsrum_humidity
sensor.vardagsrum_temp_degc
sensor.vardagsrum_battery

After renaming and reboot of Tellstick and Home Assistant:
New name in Telldus Live:
Sovrum
Gave following entities in Home Assistant:
sensor.sovrum_humidity
sensor.sovrum_temp_degc
sensor.**vardagsrum**_battery

I'm using Pre-release: 0.86

Best regards

**Comment by quazzie** [comment]
Hmm. There is no renaming of entity_id, once a sensor is created/registered with HA it should keep the entity_id unless removed or manually renamed on HA side.

What i think happened is that your sensor on telldus side got a new deviceID which in turn created new sensors in HA (vardagsrum_humidity/temp_degc), but not the battery sensor.

Are you sure you don't still have the old sensor.vardagsrum_humidity/temp_degc in HA ?
If not its strange that the humidity and temp sensors got removed/recreated but left the battery sensor.

If what i think happened is true the vardagsrum_battery sensor is not going to update.

I'll have to check this some more once i get the time.

**Comment by rodakswe** [comment]
> Hmm. There is no renaming of entity_id, once a sensor is created/registered with HA it should keep the entity_id unless removed or manually renamed on HA side.
> 
> What i think happened is that your sensor on telldus side got a new deviceID which in turn created new sensors in HA (vardagsrum_humidity/temp_degc), but not the battery sensor.
> 
> Are you sure you don't still have the old sensor.vardagsrum_humidity/temp_degc in HA ?
> If not its strange that the humidity and temp sensors got removed/recreated but left the battery sensor.
> 
> If what i think happened is true the vardagsrum_battery sensor is not going to update.
> 
> I'll have to check this some more once i get the time.

Thanks for your reply.
The sensor should not have gotten a new ID since I did not remove the battery (this usually gives Oregon sensor new ID's and recreates the sensor in Telldus Live).
All I did was a simple rename in Telldus Live.

The only leftover from "vardagsrum" is the battery sensor. I checked the core.entity_registry file.
Temperature and Humidity are now called/renamed automatically to "sovrum" and there is no battery sensor for "sovrum"

If the sensor got totally recreated I should have a new "sensor.sovrum_battery" as well. Right?

**Comment by quazzie** [comment]
Yes, you should have a new sensor.sovrum_battery also if they are new and the device on telldus reports it has battery.
if you check core.entity_registry file could you post the unique_id for the three sensors ?

**Comment by rodakswe** [comment]
> Yes, you should have a new sensor.sovrum_battery also if they are new and the device on telldus reports it has battery.
> if you check core.entity_registry file could you post the unique_id for the three sensors ?


ACCA54025C08_19_1_0 (This one is temperature "sovrum")
ACCA54025C08_19_2_0 (This one is humidity "sovrum")
ACCA54025C08_ACCA54025C08_19_battery (This one is obviously the battery, and still called the old name "vardagsrum")

None of the above are edited manually in HA, just the simple rename in Telldus Live, reboot Tellstick, reboot HA.
MQTT server is not rebooted, should I do that?

If you need any logs or anything, just point me in the right direction and I will provide what I'm capable of.

**Comment by fredrike** [comment]
My 5 cent is that this is a HA thing. You need to rename devices with unique_id using the entity registry.

**Comment by rodakswe** [comment]
> My 5 cent is that this is a HA thing. You need to rename devices with unique_id using the entity registry.

Thanks for your input, appreciated, I I'll just rename it. 
But still I think it´s strange the Temperature and Humidity got renamed even though the unique ID did not change while the Battery persisted with the old name.

**Comment by quazzie** [comment]
Haven't seen or been able to recreate this, closing until more info.
