### ISSUE TITLE
State changes not published

### ISSUE THREAD

**Issue by uphillbattle** [quazzie/tellstick-plugin-mqtt-hass#4]
Hi,

I've successfully installed your plugin (version 0.82) on my Telldus Znet Lite v2 after having Telldus install you GPG key.

I've set up the MQTT parameters and confirmed, by using `mosquitto_sub`, that the Znet does publish the list of devices connected to the Znet. The devices are even automagically discovered by Home Assistant. So far, so good.

However, the plugin does not publish state changes for the devices. If, for example, I push a button on a 433 MHz remote, the Znet registers this and I can see the change in an HA entity that fetches its state from the Telldus Live HA-integration, but a corresponding MQTT message is never published.

I might be doing something wrong or misunderstanding the plugin's use (wouldn't be the first time).

I'd appreciate it if you could give me a pointer to what I might have missed.

Best regards,
 - Tom

**Comment by quazzie** [comment]
could you capture all the messages sent to "<base topic>/<device name>/debug" topic ?
<base topic> and <device name> is set in the config for the plugin.
I have not tested this with a 433 remote so it might be something missing in the plugin.

**Comment by uphillbattle** [comment]
Thank you for responding so (extremely) quickly, but: 
**Ouch**, I feel stupid (more than usual): 
I did a reboot of the Znet and now the plugin publishes signals and changes just as I expected.
Sorry to have raised a non-existent issue, I should have rebooted first.

**Comment by uphillbattle** [comment]
The Znet sees the 433 remote as a switch, by the way and the plugin reports button pushes like this:

```
homeassistant/switch/znet/12/state ON
homeassistant/switch/znet/12/state ON
homeassistant/switch/znet/12/state ON
homeassistant/switch/znet/12/state ON

```

It keeps publishing for as long as you keep the button pushed. It means, I guess, that I should do some filtering in HA if the button pushing triggers automations.

Anyways, thanks for your good work!
