### ISSUE TITLE
Any hints to debug?

### ISSUE THREAD

**Issue by henripalmroth** [quazzie/tellstick-plugin-mqtt-hass#6]
Hi,
This is not a feature request or bug. It would be just nice to have some tips on the readme how to debug the setup. I have added the key through Telldus support and have successfully installed the plugin. However yet nothing on MQTT. How could I check what is wrong?
Br,
Henri

**Comment by uphillbattle** [comment]
Start an MQTT subscribe (for example `mosquitto_sub` if you have that installed somewhere) and subscribe to the «Base topic» or «Autodiscovery topic» that you entered when setting up the plugin. If all is well, you’ll see messages published to these topics.

Additionally, reboot the Telldus after setting up the plugin. I didn’t at first, and a reboot solved a few issues.

**Comment by henripalmroth** [comment]
Thanks for the suggestions. Got success. I changed hassio.local to IP and it worked. 

Now I just need to figure out how to change Home Assistant Telldus (local) integration to MQTT.
