### ISSUE TITLE
Can not change the MQTT hostname

### ISSUE THREAD

**Issue by chripall** [quazzie/tellstick-plugin-mqtt-hass#7]
pluging Version: 0.82.3
TellStick is currently running stable version 1.2.0

Trying to change the MQTT hostname from 10.10.10.100 to 10.10.20.100.
Hitting save will not set the new hostname. 
Rebooting after hitting save will not set the new hostname.

<img width="644" alt="Screenshot 2020-01-11 at 17 18 25" src="https://user-images.githubusercontent.com/54028395/72207409-34e0a680-3499-11ea-8b80-86304bf373f2.png">

Reinstalling the plugin will not fix the problem.

**Comment by quazzie** [comment]
Hmm, i can't seem to reproduce.
Could you bring up the developer tools (F12 in chrome) and see if there are any errors when pressing the save button ?

**Comment by quazzie** [comment]
Tellstick should have version 1.3.1 now. Is your updated and do you still have this problem ?

**Comment by quazzie** [comment]
Closing, reopen if you this is still an issue.
